
MAX_LENGTH = "max_length"
MIN_LENGTH = "min_length"
VALIDATORS = "validators"
READ_ONLY = "read_only"
WRITE_ONLY = "write_only"
REQUIRED = "required"
LABEL = "label"
HELP_TEXT = "help_text"
ALLOW_NULL = "allow_null"
ALLOW_BLANK = "allow_blank"
MAX_VALUE = "max_value"
MIN_VALUE = "min_value"
DEFAULT = "default"
FORMAT = "format"